name: generate-all-sbom

on:
  workflow_dispatch:

jobs:
  gen-sbom-for-repo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: joshjohanning/generate-sbom-action@joshjohanning/add-org-to-og
      # with:
      #   token: ${{ secrets.PAT }}
      #   resource: ${{ github.repository }}
    - uses: actions/upload-artifact@v3
      with:
        name: sbom-repo
        path: sbom-*.json

  gen-sbom-for-org:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: joshjohanning/generate-sbom-action@joshjohanning/add-org-to-og
      with:
        token: ${{ secrets.PAT }}
        resource: ${{ github.repository_owner }}
    - uses: actions/upload-artifact@v3
      with:
        name: sbom-org
        path: sbom-*.json

  gen-sbom-for-org-rate-limit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: joshjohanning/generate-sbom-action@joshjohanning/add-org-to-og
      with:
        token: ''
        resource: octodemo
    - uses: actions/upload-artifact@v3
      with:
        name: sbom-org-rate-limit
        path: sbom-*.json
