name: generate-all-sbom

on:
  workflow_dispatch:

jobs:
  gen-sbom-for-repo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: joshjohanning/generate-sbom-action@joshjohanning/add-org-to-og
      id: gensbom
    - uses: actions/upload-artifact@v3
      with:
        name: sbom
        path: ${{ steps.gensbom.outputs.fileName }}

  gen-sbom-for-org:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: joshjohanning/generate-sbom-action@joshjohanning/add-org-to-og
      id: gensbom
      with:
        token: ${{ secrets.PAT }}
        resource: ${{ github.repository_owner }}
    - uses: actions/upload-artifact@v3
      with:
        name: sbom-${{ github.repository_owner }}
        path: ${{ steps.gensbom.outputs.fileName }}

  gen-sbom-for-org-rate-limit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: joshjohanning/generate-sbom-action@joshjohanning/add-org-to-og
      id: gensbom
      with:
        token: ''
        resource: octodemo
    - uses: actions/upload-artifact@v3
      with:
        name: sbom-octodemo
        path: ${{ steps.gensbom.outputs.fileName }}
