name: generate-all-sbom

on:
  workflow_dispatch:

jobs:
  gen-sbom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: joshjohanning/generate-sbom-action@main
      with:
        token: ${{ secrets.PAT }}
        org: ${{ github.repository_owner }}
    - uses: actions/upload-artifact@v3
      with:
        name: sbom
        path: sbom-*.json
